# Run tests (slightly modified from https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html)
name: Test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test